tt  = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(tt))
print('Só tem espaços? ',tt.isspace())
print('É um numero? ', tt.isnumeric())
print('É alfabetico? ',tt.isalpha())
print('É alfanumerico? ', tt.isalnum())
print('É maiusculo? ', tt.isupper())
print('É minusculo? {}'.format(tt.islower()))
print('Está capitalizado? {}'.format(tt.istitle()))